const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const PORT=Number(process.env.PORT||3000);
const rooms=new Map(), clients=new Map();
const id=()=>Math.random().toString(36).slice(2,9).toUpperCase();
function frame(txt){const b=Buffer.from(txt),n=b.length; if(n<126)return Buffer.concat([Buffer.from([129,n]),b]); if(n<65536){const h=Buffer.alloc(4);h[0]=129;h[1]=126;h.writeUInt16BE(n,2);return Buffer.concat([h,b])}const h=Buffer.alloc(10);h[0]=129;h[1]=127;h.writeBigUInt64BE(BigInt(n),2);return Buffer.concat([h,b])}
function send(p,o){if(p.sock.destroyed)return;p.sock.write(frame(JSON.stringify(o)))}
function broadcast(room,o){for(const p of room.players)send(p,o)}
function state(r){return r.players.map(p=>({id:p.id,name:p.name,x:p.x,z:p.z,speed:p.speed,heading:p.heading,car:p.car}))}
function leave(p){if(!p.room)return;const r=rooms.get(p.room);if(!r)return;r.players=r.players.filter(x=>x!==p);if(!r.players.length)rooms.delete(r.code);else broadcast(r,{type:"roomState",players:state(r)});p.room=null}
function msg(p,m){
 if(m.type==="host"){leave(p);let c;do c=id().slice(0,4);while(rooms.has(c));let r={code:c,players:[]};rooms.set(c,r);p.name=String(m.name||"Driver").slice(0,20);p.room=c;r.players.push(p);send(p,{type:"roomCreated",room:c});broadcast(r,{type:"roomState",players:state(r)});return}
 if(m.type==="join"){leave(p);let r=rooms.get(String(m.room||"").toUpperCase());if(!r)return send(p,{type:"error",message:"Room not found"});if(r.players.length>=8)return send(p,{type:"error",message:"Room full"});p.name=String(m.name||"Driver").slice(0,20);p.room=r.code;r.players.push(p);send(p,{type:"joined",room:r.code});broadcast(r,{type:"roomState",players:state(r)});return}
 const r=p.room&&rooms.get(p.room);if(!r)return;
 if(m.type==="state"){p.x=Number(m.x)||0;p.z=Number(m.z)||0;p.speed=Number(m.speed)||0;p.heading=Number(m.heading)||0;p.car=Number(m.car)||0;broadcast(r,{type:"roomState",players:state(r)})}
}
const server=http.createServer((req,res)=>{let f=(req.url||"/").split("?")[0];if(f==="/")f="/index.html";const full=path.join(__dirname,path.normalize(f));if(!full.startsWith(__dirname)){res.writeHead(403);return res.end()}fs.readFile(full,(e,d)=>{if(e){res.writeHead(404);return res.end("Not found")}const ext=path.extname(full);const type={".html":"text/html",".js":"text/javascript",".css":"text/css"}[ext]||"application/octet-stream";res.writeHead(200,{"Content-Type":type,"Cache-Control":"no-store"});res.end(d)})});
server.on("upgrade",(req,sock)=>{const key=req.headers["sec-websocket-key"];if(!key)return sock.destroy();const accept=crypto.createHash("sha1").update(key+"258EAFA5-E914-47DA-95CA-C5AB0DC85B11").digest("base64");sock.write("HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: "+accept+"\r\n\r\n");const p={sock,id:id(),name:"Driver",room:null,x:0,z:0,speed:0,heading:0,car:0};clients.set(sock,p);send(p,{type:"welcome",id:p.id});let buf=Buffer.alloc(0);sock.on("data",c=>{buf=Buffer.concat([buf,c]);while(buf.length>=2){let n=buf[1]&127,off=2;if(n===126){if(buf.length<4)break;n=buf.readUInt16BE(2);off=4}else if(n===127){if(buf.length<10)break;n=Number(buf.readBigUInt64BE(2));off=10}const masked=!!(buf[1]&128);if(masked)off+=4;if(buf.length<off+n)break;let pl=buf.subarray(off,off+n);if(masked){const mk=buf.subarray(off-4,off),q=Buffer.alloc(n);for(let i=0;i<n;i++)q[i]=pl[i]^mk[i%4];pl=q}const opcode=buf[0]&15;buf=buf.subarray(off+n);if(opcode===8)return sock.end();if(opcode!==1)continue;try{msg(p,JSON.parse(pl.toString()))}catch(e){}}});sock.on("close",()=>{leave(p);clients.delete(sock)});sock.on("error",()=>{leave(p);clients.delete(sock)})});
server.listen(PORT,"0.0.0.0",()=>console.log("Police Chase 3D REMASTER online server listening on port "+PORT));
